### ISSUE TITLE
请求更新到2.4.3版本的creator，非常感谢，可以有偿！期待得到您及时的回复~~

### ISSUE THREAD

**Issue by AnkoGo** [chenbenying/creator-2.1.3-shader-card#1]
请求更新到2.4.3版本的creator，非常感谢，可以有偿！期待得到您及时的回复~~

**Comment by chenbenying** [comment]
我试了一下，好像是不兼容哦，等我弄好了再通知你

**Comment by chenbenying** [comment]
> 请求更新到2.4.3版本的creator，非常感谢，可以有偿！期待得到您及时的回复~~

**Comment by chenbenying** [comment]
> 请求更新到2.4.3版本的creator，非常感谢，可以有偿！期待得到您及时的回复~~

https://github.com/chenbenying/cocos-creator-2.4.3shader-card
已经弄好了，去下载吧

**Comment by AnkoGo** [comment]
非常感谢，请问下边沿阴影是怎么做的？真不会shade
